# Generated by Django 2.1.2 on 2019-05-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('5', '위급'), ('4', '긴급'), ('3', '평범'), ('2', '여유'), ('1', '사소')], max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
